In [2]:
import numpy as np

In [3]:
from numpy.random import randn

In [3]:
data = {i : randn() for i in range(7)}

In [4]:
data

{0: 0.3789805008911148,
 1: -1.4627422201642941,
 2: -0.6856772116386456,
 3: 0.24634478403896043,
 4: 1.3009762323823677,
 5: 0.6924149862461378,
 6: 0.8598771831526589}

In [5]:
# numpy 的ndarray 多维数组对象
data1 = [6, 7.5, 8, 0, 1]

In [6]:
arr1 = np.array(data1)

In [7]:
arr1 #一维数组

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
# 多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim# 显示维度

2

In [11]:
arr2.shape #表示各维度大小的一个元组

(2, 4)

In [12]:
arr2.dtype# 数据类型，array中数据类型必须一致

dtype('int64')

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

In [15]:
# 创建数组的其他函数
np.zeros(10)# 创建全是0的数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
a = np.zeros((5, 3, 4))# 第三个维度

In [18]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
b = np.zeros((2, 3, 4, 5))# 多维度

In [20]:
b

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [21]:
np.empty((2, 3)) #返回地是未初始化的垃圾值，并不是全0， 只分配内存空间

array([[6.95330725e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [22]:
np.arange(15) #range的数组版, 返回一个ndarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

range(0, 15)

In [23]:
np.eye(4)# 创建正方形数组，对角线是1其余是0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.identity(4)# 同上

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# 数据类型
# 数据类型转换 astype
# 调用astype总是会创建一个新的数组，是原始数据的一份拷贝
arr = np.array([1,2,3,4])

In [26]:
arr.dtype

dtype('int64')

In [27]:
floart_arr = arr.astype(np.float64)

In [28]:
floart_arr.dtype

dtype('float64')

In [29]:
int_array = np.arange(10)

In [30]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
calibers = np.array([.22, .33], dtype = np.float64)

In [83]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
# 索引
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5]

5

In [7]:
arr[5:8]

array([5, 6, 7])

In [8]:
arr[5:8] = 12

In [10]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [12]:
# 切片并不会复制数据，切片中的修改会体现在原数据上
arr_slice = arr[5:8]

In [13]:
arr_slice[1] = 123456

In [14]:
arr

array([     0,      1,      2,      3,      4,     12, 123456,     12,
            8,      9])

In [19]:
# 转置
arr = np.arange(15).reshape((3, 5))

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [22]:
arr = np.random.randn(6, 3)

In [23]:
np.dot(arr.T, arr)

array([[11.76345562,  1.79138545, -7.07845153],
       [ 1.79138545,  3.98644491, -2.06368523],
       [-7.07845153, -2.06368523,  6.10481721]])

In [29]:
# 比较两个数组并返回大的那个
x = randn(8)
y = randn(8)

In [30]:
x


array([ 0.08592743,  1.35548961,  1.77916086, -0.32607557,  0.60078726,
       -0.14278784,  0.2310231 , -0.54530752])

In [31]:
y

array([ 1.11981231,  0.85150911,  1.00115589,  0.98583034, -1.75476497,
        0.56350907, -0.2597034 ,  1.62754918])

In [32]:
np.maximum(x, y)

array([1.11981231, 1.35548961, 1.77916086, 0.98583034, 0.60078726,
       0.56350907, 0.2310231 , 1.62754918])