In [2]:
import numpy as np

In [5]:
from numpy.random import randn

In [6]:
data = {i : randn() for i in range(7)}

In [7]:
data

{0: 0.01466171264791566,
 1: 0.27821164405423787,
 2: -0.539224847831443,
 3: -0.5977879244264162,
 4: 0.653033617045964,
 5: -0.1451025530811338,
 6: -0.23754871383881576}

In [12]:
# numpy 的ndarray 多维数组对象
data1 = [6, 7.5, 8, 0, 1]

In [16]:
arr1 = np.array(data1)

In [19]:
arr1 #一维数组

array([6. , 7.5, 8. , 0. , 1. ])

In [20]:
# 多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr2.ndim# 显示维度

2

In [35]:
arr2.shape #表示各维度大小的一个元组

(2, 4)

In [36]:
arr2.dtype# 数据类型，array中数据类型必须一致

dtype('int64')

In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2.dtype

dtype('int64')

In [46]:
# 创建数组的其他函数
np.zeros(10)# 创建全是0的数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
a = np.zeros((5, 3, 4))# 第三个维度

In [64]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
b = np.zeros((2, 3, 4, 5))# 多维度

In [68]:
b

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [69]:
np.empty((2, 3)) #返回地是未初始化的垃圾值，并不是全0， 只分配内存空间

array([[6.95333436e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [70]:
np.arange(15) #range的数组版, 返回一个ndarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

range(0, 15)

In [74]:
np.eye(4)# 创建正方形数组，对角线是1其余是0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
np.identity(4)# 同上

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
# 数据类型
# 数据类型转换 astype
# 调用astype总是会创建一个新的数组，是原始数据的一份拷贝
arr = np.array([1,2,3,4])

In [77]:
arr.dtype

dtype('int64')

In [78]:
floart_arr = arr.astype(np.float64)

In [79]:
floart_arr.dtype

dtype('float64')

In [80]:
int_array = np.arange(10)

In [81]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
calibers = np.array([.22, .33], dtype = np.float64)

In [83]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])