## 实现一个softmax函数

In [2]:
# 简单实现
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

In [3]:
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [4]:
sum_exp_A = np.sum(exp_a)
print(sum_exp_A)

74.1221542101633


In [5]:
y = exp_a / sum_exp_A

In [6]:
y

array([0.01821127, 0.24519181, 0.73659691])

In [7]:
# 函数式
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y 

In [10]:
a = np.array([1010, 1000, 990])
softmax(a)

/var/folders/dl/j2ph6ksd6s79dy9wbfmdyz6c0000gn/T/ipykernel_25017/4002247644.py:3: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
/var/folders/dl/j2ph6ksd6s79dy9wbfmdyz6c0000gn/T/ipykernel_25017/4002247644.py:5: RuntimeWarning: invalid value encountered in true_divide
  y = exp_a / sum_exp_a


array([nan, nan, nan])

In [11]:
c = np.max(a)
a - c
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [4]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [13]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y, np.sum(y))

[0.01821127 0.24519181 0.73659691] 1.0


In [6]:
from tensorflow import keras
import tensorflow as tf

In [7]:
(x_train, t_train), (x_test, t_test) = keras.datasets.mnist.load_data()

In [8]:
print(x_train.shape)

(60000, 28, 28)


In [9]:
print(t_train.shape)

(60000,)


In [10]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [14]:
img = x_train[0]
label = t_train[0]
print(label)

5


In [22]:
from PIL import Image
import numpy as np

In [16]:
print(img.shape)
img = img.reshape(28, 28)
print(img.shape)

(784,)
(28, 28)


In [23]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

In [25]:
img_show(img)

## 神经网络的推理处理

In [15]:
# 定义函数来完成神经网络的推导

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def init_network():
    with open("/Users/yudd/Github/DeepLearningFromScratch/ch03/sample_weight.pkl", "rb") as f:
        network = pickle.load(f)
        
    return network


def predict(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(z2)
    
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y

In [ ]:
x, t = get_data()
network = init_network()
accuracy_cnt = 0
for i in range(len(x)):
 y = predict(network, x[i])
 p = np.argmax(y) # 获取概率最高的元素的索引
 if p == t[i]:
 accuracy_cnt += 1
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

In [21]:
x = np.array([[0.1, 0.8, 0.1], [0.3, 0.1, 0.6],[0.2, 0.5, 0.3], [0.8, 0.1, 0.1]])
x

array([[0.1, 0.8, 0.1],
       [0.3, 0.1, 0.6],
       [0.2, 0.5, 0.3],
       [0.8, 0.1, 0.1]])

In [25]:
y = np.argmax(x, axis=1) # 获取最大元素的索引

In [26]:
print(y)

[1 2 1 0]


In [1]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

In [3]:
def mean_squard_error(y, t):
    return 0.5 * np.sum((y - t) ** 2)

In [4]:
mean_squard_error(np.array(y), np.array(t))

0.09750000000000003

In [5]:
# 定义一个交叉熵函数

def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [6]:
np.log?